version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: file_hosting_redis
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: file_hosting_server
    restart: always