version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: file_hosting_redis
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8000"
    environment:
      NGINX_PORT: 81
      NGINX_ADDRESS: 127.0.0.1
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: redis:6379
    container_name: file_hosting_server
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "81:81"
    depends_on:
      - app
    restart: always